export const assets = {
  home: {
    hero: {
      avatarSmile: require('@images/home/hero/avatar-smile.webp'),
      dribble: require('@images/home/hero/dribble.webp'),
      github: require('@images/home/hero/github.webp'),
      instagram: require('@images/home/hero/instagram.webp'),
      linkedin: require('@images/home/hero/linkedin.webp'),
      quadrilateral: require('@images/home/hero/quadrilateral.webp'),
      triangle: require('@images/home/hero/triangle.webp'),
      twistedTorus: require('@images/home/hero/twisted-torus.webp'),
      zigZag: require('@images/home/hero/zig-zag.webp'),
    },
    letsConnect: {
      avatarBigSmile: require('@images/home/letsConnect/avatar-big-smile.webp'),
      dribble: require('@images/home/letsConnect/twitter.png'),
      github: require('@images/home/letsConnect/github.webp'),
      gmail: require('@images/home/letsConnect/gmail.webp'),
      instagram: require('@images/home/letsConnect/instagram.webp'),
      linkedin: require('@images/home/letsConnect/linkedin.webp'),
    },
    myLatestProject: {
      figma: require('@images/home/myLatestProject/figma.webp'),
      rocket: require('@images/home/myLatestProject/rocket.webp'),
      suitcase: require('@images/home/myLatestProject/suitcase.webp'),
      projects: {
        portfolioWebsite: require('@images/home/myLatestProject/projects/portfolio-website.webp'),
      },
    },
    quote: {
      bulb: require('@images/home/quote/bulb.webp'),
      heart: require('@images/home/quote/heart.webp'),
      paintKit: require('@images/home/quote/paint-kit.webp'),
      teaCup: require('@images/home/quote/tea-cup.webp'),
    },
    technologyStack: {
      expressJs: require('@images/home/technologyStack/express-js.webp'),
      javascript: require('@images/home/technologyStack/javascript.webp'),
      nextJs: require('@images/home/technologyStack/next-js.webp'),
      reactJs: require('@images/home/technologyStack/react-js.webp'),
      reactNative: require('@images/home/technologyStack/react-native.webp'),
      tailwindCss: require('@images/home/technologyStack/tailwindcss.webp'),
      typescript: require('@images/home/technologyStack/typescript.webp'),
      nodejs: require('@images/home/technologyStack/node-js.png'),
      postgres: require('@images/home/technologyStack/postgresql.png'),
      mysql: require('@images/home/technologyStack/mysql.png'),
      mongodb: require('@images/home/technologyStack/mongodb.png'),
      sequelize: require('@images/home/technologyStack/sequelize.png'),
      redis: require('@images/home/technologyStack/redis.png'),
      socket: require('@images/home/technologyStack/socket.png'),
      docker: require('@images/home/technologyStack/docker.png'),
      kafka: require('@images/home/technologyStack/kafka.png'),
      aws: require('@images/home/technologyStack/aws.png'),
    },
  },
};
